### ISSUE TITLE
Crashes when used in the App Store

### ISSUE THREAD

**Issue by ir-fuel** [rocketmade/RMAppStoreVersionCheck#1]
I integrated this in my code, and as soon as a new version of my app appeared and got downloaded on the device, the app crashes in this code.

It is because:

NSMutableDictionary *knownVersions = [[NSUserDefaults standardUserDefaults] objectForKey:kUserDefaultsVersionCheckKey];

actually returns an NSDictionary, and not an NSMutableDictionary.

a few lines later this dictionary gets modified which crashes the app

**Comment by enzosv** [comment]
I've experienced this problem on my app as well. Right when iTunesConnect closed for Christmas as well. It was hell. Anyway, the fix I have now is to replace

NSMutableDictionary *knownVersions = [[NSUserDefaults standardUserDefaults] 

with this line

NSMutableDictionary *knownVersions = [[NSMutableDictionary alloc] initWithDictionary:[[NSUserDefaults standardUserDefaults] objectForKey:kUserDefaultsVersionCheckKey]];

**Comment by brandonroth** [comment]
Thanks for the bug report, this should be fixed now.
